### ISSUE TITLE
Links to drafts don't work

### ISSUE THREAD

**Issue by KenjiBaheux** [martinthomson/escape-report#7]
Could be just me but github is serving a 404 for:
 - Editor's Copy
 - Compare Editor's Copy to Individual Draft

**Comment by martinthomson** [comment]
Yeah, I couldn't work this out yesterday.  The content is there on the branch and everything is configured correctly, but it just doesn't work.  That's never happened before, so I don't know what to do.

**Comment by martinthomson** [comment]
OK, I turned it off and on again and now it seems to be online.  An by-product of this originally being  a  private repo, I guess.
